### ISSUE TITLE
ArgumentError: argument 1: <type 'exceptions.TypeError'>: wrong type

### ISSUE THREAD

**Issue by vah13** [MarioVilas/winappdbg#37]
Hi there, 
I'd like to hook SHUnicodeToAnsi from ShLwApi.dll DLL using this code 
```
        if module.match_name("ShLwApi.dll"):
            pid = event.get_pid()
            address = module.resolve("SHUnicodeToAnsi")
            signature = (LPCWSTR, LPWSTR, INT)
            event.debug.hook_function(pid, address, SHUnicodeToAnsi, signature=signature)
```

but I'm getting this error 
```
C:\Python27\lib\site-packages\winappdbg\event.py:1853: EventCallbackWarning: Event handler pre-callback <__main__.MyEventHandler object at 0x02B14C10> raised an exception: Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\winappdbg\event.py", line 1848, in dispatch
    returnValue = self.__eventHandler(event)
  File "C:\Python27\lib\site-packages\winappdbg\event.py", line 1465, in __call__
    return method(event)
  File "C:/Users/vvvaa/PycharmProjects/zipper1/main.py", line 44, in load_dll
    event.debug.hook_function(pid, address, SHUnicodeToAnsi, signature=signature)
  File "C:\Python27\lib\site-packages\winappdbg\breakpoint.py", line 4047, in hook_function
    hookObj = Hook(preCB, postCB, paramCount, signature, arch)
  File "C:\Python27\lib\site-packages\winappdbg\breakpoint.py", line 1048, in __new__
    return _Hook_i386(*argv, **argd)
  File "C:\Python27\lib\site-packages\winappdbg\breakpoint.py", line 1138, in __init__
    self._signature = self._calc_signature(signature)
  File "C:\Python27\lib\site-packages\winappdbg\breakpoint.py", line 1440, in _calc_signature
    self._cast_signature_pointers_to_void(signature)
  File "C:\Python27\lib\site-packages\winappdbg\breakpoint.py", line 1152, in _cast_signature_pointers_to_void
    signature[i] = cast(t, c_void_p)
  File "C:\Python27\lib\ctypes\__init__.py", line 503, in cast
    return _cast(obj, obj, typ)
ArgumentError: argument 1: <type 'exceptions.TypeError'>: wrong type

  warnings.warn(msg, EventCallbackWarning)
```
I saw that SHUnicodeToAnsi function has 3 arguments 
```
; int __stdcall SHUnicodeToUnicode(LPCWSTR pwzSrc, LPWSTR pwzDst, int cwchBuf)
pwzSrc= dword ptr  4
pwzDst= dword ptr  8
cwchBuf= dword ptr  0Ch
```
Could you help me what I'm doing wrong? 

*I know this is a question not issue, I'm sorry

**Comment by vah13** [comment]
using api monitor I hooked and have this call
```
SHUnicodeToAnsi ( "some text", 0x11bedee4, 260 )
```

**Comment by MarioVilas** [comment]
Hi!

Basically the problem is you can only use null pointers when specifying the signature. That's because if you use more complex pointer types, ctypes tries to be "helpful" and access those pointers for various things, and that would obviously not work since the pointer belongs to another process.

Just replacing any pointer type for LPVOID should work. Bear in mind you cannot cast those to other types and access them either, you need to use winappdbg to read the target process memory manually.

Hope that helps! :)
